# config_example.yaml
download_dir: "~/Downloads"
output_dir: "~/Downloads/Dexcom_download"
dexcom_url: "https://clarity.dexcom.eu"
chromedriver_log: os.path.join(os.getcwd(), "chromedriver.log")
chrome_user_data_dir: "~/ClarityDownloadProfile"
rapports: ["Aperçu", "Modèles", "Superposition", "Quotidien", "Statistiques", "AGP", "Export"]